//@ui5-bundle com/supabase/easyui5/Component-preload.js
sap.ui.predefine("com/supabase/easyui5/Component", ["sap/ui/core/UIComponent","sap/ui/Device","./model/models"],function(t,e,s){"use strict";return t.extend("com.supabase.easyui5.Component",{metadata:{manifest:"json"},init:function(){t.prototype.init.call(this);this.setModel(s.createDeviceModel(),"device");this.getRouter().initialize()},getContentDensityClass:function(){if(this.contentDensityClass===undefined){if(document.body.classList.contains("sapUiSizeCozy")||document.body.classList.contains("sapUiSizeCompact")){this.contentDensityClass=""}else if(!e.support.touch){this.contentDensityClass="sapUiSizeCompact"}else{this.contentDensityClass="sapUiSizeCozy"}}return this.contentDensityClass}})});
sap.ui.predefine("com/supabase/easyui5/controller/App.controller", ["./BaseController"],function(e){"use strict";return e.extend("com.supabase.easyui5.controller.App",{onInit:function(){this.getView().addStyleClass(this.getOwnerComponent().getContentDensityClass())}})});
sap.ui.predefine("com/supabase/easyui5/controller/BaseController", ["sap/ui/core/mvc/Controller","sap/ui/core/UIComponent","sap/ui/core/routing/History"],function(e,t,n){"use strict";return e.extend("com.supabase.easyui5.controller.BaseController",{getOwnerComponent:function(){return e.prototype.getOwnerComponent.call(this)},getRouter:function(){return t.getRouterFor(this)},getResourceBundle:function(){const e=this.getOwnerComponent().getModel("i18n");return e.getResourceBundle()},getModel:function(e){return this.getView().getModel(e)},setModel:function(e,t){this.getView().setModel(e,t);return this},navTo:function(e,t,n){this.getRouter().navTo(e,t,undefined,n)},onNavBack:function(){const e=n.getInstance().getPreviousHash();if(e!==undefined){window.history.go(-1)}else{this.getRouter().navTo("main",{},undefined,true)}}})});
sap.ui.predefine("com/supabase/easyui5/controller/Main.controller", ["./BaseController","sap/m/MessageBox"],function(e,o){"use strict";return e.extend("com.supabase.easyui5.controller.Main",{sayHello:function(){o.show("Hello World!")}})});
sap.ui.predefine("com/supabase/easyui5/model/formatter", function(){"use strict";return{formatValue:function(e){return e&&e.toUpperCase()}}});
sap.ui.predefine("com/supabase/easyui5/model/models", ["sap/ui/model/json/JSONModel","sap/ui/model/BindingMode","sap/ui/Device"],function(e,n,i){"use strict";return{createDeviceModel:function(){const o=new e(i);o.setDefaultBindingMode(n.OneWay);return o}}});
sap.ui.require.preload({
	"com/supabase/easyui5/i18n/i18n.properties":'appTitle=com.supabase.easyui5\nappDescription=UI5 Application com.supabase.easyui5\nbtnText=Say Hello\n',
	"com/supabase/easyui5/i18n/i18n_de.properties":'appTitle=com.supabase.easyui5\nappDescription=UI5 Application com.supabase.easyui5\nbtnText=Sag Hallo\n',
	"com/supabase/easyui5/i18n/i18n_en.properties":'appTitle=com.supabase.easyui5\nappDescription=UI5 Application com.supabase.easyui5\nbtnText=Say Hello\n',
	"com/supabase/easyui5/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"com.supabase.easyui5","type":"application","i18n":"i18n/i18n.properties","title":"{{appTitle}}","description":"{{appDescription}}","applicationVersion":{"version":"1.0.0"}},"sap.ui":{"technology":"UI5","icons":{},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"rootView":{"viewName":"com.supabase.easyui5.view.App","type":"XML","async":true,"id":"app"},"dependencies":{"minUI5Version":"1.133.0","libs":{"sap.ui.core":{},"sap.m":{}}},"handleValidation":true,"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"com.supabase.easyui5.i18n.i18n"}}},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","viewPath":"com.supabase.easyui5.view","controlId":"app","controlAggregation":"pages","async":true},"routes":[{"pattern":"","name":"main","target":"main"}],"targets":{"main":{"viewId":"main","viewName":"Main"}}}}}',
	"com/supabase/easyui5/view/App.view.xml":'<mvc:View\n\tcontrollerName="com.supabase.easyui5.controller.App"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"><App id="app" /></mvc:View>\n',
	"com/supabase/easyui5/view/Main.view.xml":'<mvc:View\n\tcontrollerName="com.supabase.easyui5.controller.Main"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"\n\txmlns:core="sap.ui.core"\n\tcore:require="{\n\t\tformatter: \'com/supabase/easyui5/model/formatter\'\n\t}"><Page\n\t\ttitle="{i18n>appTitle}"\n\t\tid="page"><content><IllustratedMessage\n\t\t\t\ttitle="{i18n>appTitle}"\n\t\t\t\tillustrationType="sapIllus-SuccessHighFive"\n\t\t\t\tenableVerticalResponsiveness="true"\n\t\t\t\tdescription="{i18n>appDescription}"><additionalContent><Button\n\t\t\t\t\t\tid="helloButton"\n\t\t\t\t\t\ttext="{formatter: \'formatter.formatValue\', path: \'i18n>btnText\'}"\n\t\t\t\t\t\tpress="sayHello" /></additionalContent></IllustratedMessage></content></Page></mvc:View>\n'
});
//# sourceMappingURL=Component-preload.js.map
